name: Trigger S3 Upload

on:
  push:
    branches:
      - main  # This will trigger on pushes to main
  workflow_dispatch:  # This allows manual triggering

jobs:
  call-upload-workflow:
    uses: ./.github/workflows/upload-binaries-to-s3.yml
    with:
      region: "eu-west-2"  # Change to your AWS region
    secrets:
      bucket_name: ${{ secrets.AWS_S3_BUCKET }}
      role_to_assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}