name: Upload Repository Files to S3

on:
  workflow_call:
    inputs:
      region:
        description: The AWS region to upload the files to.
        type: string
        required: true
    secrets:
      bucket_name:
        description: The name of the S3 bucket to upload the files to.
        required: true
      role_to_assume:
        description: The role to assume for the S3 bucket.
        required: true

jobs:
  upload_files:
    name: Upload Files to S3
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ inputs.region }}
          role-to-assume: ${{ secrets.role_to_assume }}

      - name: Upload binaries to S3
        run: aws s3 sync . s3://${{ secrets.bucket_name }}/ --exclude "LICENSE" --exclude "Readme.md" --exclude ".github/*" --exclude ".git/*"